name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  animated_splash_screen: ^1.3.0
  google_fonts: ^6.0.0
  carousel_slider: ^5.0.0
  image_picker: ^1.0.7
  path_provider: ^2.0.15
  http: ^1.2.0
  shared_preferences: ^2.2.2
  flutter_speed_dial: ^7.0.0

  # Firebase dependencies can be kept if you still use authentication or Firestore
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.6.12
  firebase_messaging: 15.2.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/my_assets.png
    - assets/images/image1.jpg
    - assets/images/image2.jpg
    - assets/images/image3.jpg
    - assets/images/image4.jpg
    - assets/images/image5.jpg
    - assets/default_avatar.png # <-- ensure the extension matches your asset file
